# Generated by Django 5.1.6 on 2025-02-20 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('rotation', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('audio_file', models.URLField(max_length=500)),
                ('cover_art', models.URLField(blank=True, max_length=500)),
                ('lyrics_file', models.URLField(blank=True, max_length=500)),
                ('intro_point', models.FloatField(default=0)),
                ('vocal_point', models.FloatField(default=0)),
                ('aux_point', models.FloatField(default=0)),
                ('allow_skip', models.BooleanField(default=False)),
                ('is_clean', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
