# Generated by Django 5.1.6 on 2025-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiocms', '0002_playlist_playlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='rotation',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
