# Generated by Django 5.1.6 on 2025-03-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0005_category_stationid'),
        ('radiocms', '0003_playlistitem_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='library_items', to='airadio.category'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='playlist_items', to='airadio.category'),
        ),
    ]
