# Generated by Django 5.1.6 on 2025-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#7ac5be', max_length=7, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
                'db_table': 'formats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover_art', models.URLField(blank=True, null=True, verbose_name='Cover Art URL')),
                ('media_url', models.URLField(verbose_name='Media URL')),
                ('published_at', models.DateTimeField(verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'podcasts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='library',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='library_items', to='airadio.format'),
        ),
    ]
