# Generated by Django 5.1.6 on 2025-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0002_format_podcast_library_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='retail',
            field=models.CharField(default='', max_length=255, verbose_name='Retail'),
            preserve_default=False,
        ),
    ]
