# Generated by Django 5.1.6 on 2025-03-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0005_category_stationid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
